# Generated by Django 4.1.1 on 2023-08-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_licenseapplication_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Expired', 'Expired'), ('Declined', 'Declined'), ('Approved - (Pending Payment)', 'Approved (Pending Payment)'), ('Approved - (Paid)', 'Approved (Paid)')], default='Pending', max_length=50),
        ),
    ]
